name: "Node Code Lint and Formatter"
description: "Formats your code automatically using your choosen lint and format scripts [yarn/npm]! No configuration - it just works."
author: "MarvinJWendt && Beau Williams"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
