name: "Node Lint And Format Action"
description: "Lints and formats your code automatically using your npm/yarn scripts defined in package.json! No configuration - it just works."
author: "MarvinJWendt && Beau Williams"
branding:
  icon: check
  color: green
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
