name: "Node Format and Lint CI"
description: "Formats your code automatically using your choosen formatters! No configuration - it just works."
author: "MarvinJWendt && Beau Williams"
branding:
  icon: check
  color: green
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
