name: "Node Lint And Format"
description: "Recently Updated. Lints and formats your code automatically using your npm/yarn scripts defined in package.json!"
author: "MarvinJWendt && Beau Williams"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
